import { AuthProvider } from "@/hooks/UseAuth";
import { PropsWithChildren } from "react";
import Header from "../components/Header";
import "./App.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
        />
        <meta charSet="UTF-8" />
      </head>
      <body>
        <section>
          <Header />
        </section>
        <section className="section">
          <AuthProvider>{children}</AuthProvider>
        </section>
      </body>
    </html>
  );
};

export default RootLayout;
